- name: variable preference
  hosts: local
  connection: local
  vars:
    NAME: variable from Play Level
  # vars_files:
  # - Course.yml
  # vars_prompt:
  # - name: NAME
  #   prompt: what is your NAME?
  #   private: false
  tasks:
  - name: Testing variable preference
    # vars:
    #   NAME: from Task Level
    ansible.builtin.debug:
      msg: "Name :{{ NAME }}"



 ## 1.  from_Command_level"
 ## 2.  from Task Level"
 ## 3.  from file Level"
 ## 4.  from prompt level
 ## 5.  from Play Level
 ## 6.  from Invertory Level



