- name: install the packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.Package:
      name: "{{ item }}"  ### Here item is Reserved Key word....
      state: latest
    loop:
    - nginx
    - mysql
    - zip