- name: install the packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"  ### Here item is Reserved Key word....
      state: "{{ item.state }}"
    loop:
    - { name: "nginx", state: "absent" } 
    - { name: "mysql", state: "absent" }
    - { name: "zip", state: "latest" } 